apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    isDefault: true
    url: http://localhost:8086
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: weather
    secureJsonData:
      token: ${INFLUX_TOKEN}
